name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [esp32, esp32c3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with ESP-IDF v6.0
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0
          target: ${{ matrix.target }}
